module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  concerned: /publications/persons-concerned/:slug/
taxonomies:
  concerned: concerned