module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

# Default
permalinks:
  concerned: /publications/:slug/
taxonomies:
  concerned: concerned